repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 60ef368a6f48dfb4317651017f66dbb055241a6c  # frozen: v0.12.12
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 412de98d50e846f31ea6f4b0ad036f2c24a7a024  # frozen: v1.17.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --explicit-package-bases]

  - repo: https://github.com/pycqa/bandit
    rev: 2d0b675b04c80ae42277e10500db06a0a37bae17  # frozen: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009]

  # Database migration specific checks
  - repo: local
    hooks:
      - id: migration-version-check
        name: Check migration version sequence
        entry: python scripts/check_migration_versions.py
        language: python
        files: ^src/zulip_refinement_bot/migrations/versions/.*\.py$
        pass_filenames: false

      - id: migration-test-coverage
        name: Ensure migration tests exist
        entry: python scripts/check_migration_test_coverage.py
        language: python
        files: ^src/zulip_refinement_bot/migrations/versions/.*\.py$
        pass_filenames: false

      - id: database-schema-validation
        name: Validate database schema consistency
        entry: python scripts/validate_schema_consistency.py
        language: python
        files: ^src/zulip_refinement_bot/(migrations|database).*\.py$
        pass_filenames: false
