name: zulip-refinement-bot
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - httpx>=0.24.0
  - sqlite
  - pytest>=7.0
  - pytest-cov
  - pytest-asyncio
  - flake8
  - mypy
  - pre-commit
  - ruff
  - zulip>=0.8.0
  - python-dotenv>=1.0.0
  - pydantic>=2.0.0
  - pydantic-settings>=2.0.0
  - structlog>=23.0.0
  - rich>=13.0.0
  - typer>=0.9.0
  - holidays>=0.34
  - fastapi>=0.100.0
  - uvicorn>=0.23.0
